# Generated by Django 3.1.7 on 2021-05-10 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokens', '0002_auto_20210316_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='uses',
            field=models.IntegerField(default=1),
        ),
    ]
