# Generated by Django 3.1.7 on 2021-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_squashed_0010_auto_20210324_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
