# Generated by Django 3.1.7 on 2021-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='popularity',
            field=models.BigIntegerField(),
        ),
    ]
