# Generated by Django 3.1.7 on 2021-04-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210401_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='popularity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='posts.tag'),
        ),
    ]
