# Generated by Django 3.1.6 on 2021-03-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210316_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='children',
        ),
        migrations.AlterField(
            model_name='post',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='posts.Post'),
        ),
    ]
