# Generated by Django 3.1.7 on 2021-03-24 20:18

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20210322_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=posts.models.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
