# Generated by Django 3.1.7 on 2021-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210510_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descendants',
            field=models.IntegerField(default=0),
        ),
    ]
